export interface Product {
  id: string
  name: string
  category: "electronics" | "appliances" | "perfumes"
  price: number
  image: string
  description: string
  brand: string
  rating: number
  reviews: number
  inStock: boolean
  weight?: number // Peso en kg para cálculo de envío
  featured?: boolean
}

export const products: Product[] = [
  {
    id: "1",
    name: "iPhone 17 Pro Max",
    category: "electronics",
    price: 1299,
    image: "https://i.ebayimg.com/images/g/zcgAAeSw~d5owejX/s-l600.jpg",
    description: "El smartphone más avanzado con chip A19 Pro y cámara profesional",
    brand: "Apple",
    rating: 4.9,
    reviews: 1234,
    inStock: true,
    weight: 0.22, // 220g
    featured: true,
  },
  {
    id: "2",
    name: 'MacBook Pro 16"',
    category: "electronics",
    price: 2499,
    image: "/macbook-pro-16-inch-laptop-premium.jpg",
    description: "Potencia extrema con chip M3 Max para profesionales creativos",
    brand: "Apple",
    rating: 4.8,
    reviews: 987,
    inStock: true,
    weight: 1.6, // 1.6kg
    featured: true,
  },
  {
    id: "3",
    name: "Sony WH-1000XM5",
    category: "electronics",
    price: 399,
    image: "/sony-premium-noise-cancelling-headphones.jpg",
    description: "Auriculares premium con cancelación de ruido líder en la industria",
    brand: "Sony",
    rating: 4.7,
    reviews: 892,
    inStock: true,
    weight: 0.25, // 250g
    featured: true,
  },
  {
    id: "4",
    name: 'Samsung OLED 4K 65"',
    category: "appliances",
    price: 1899,
    image: "/samsung-oled-tv-65-inch-premium.jpg",
    description: "Televisor OLED 4K con calidad de imagen cinematográfica",
    brand: "Samsung",
    rating: 4.9,
    reviews: 543,
    inStock: true,
    weight: 18.5, // 18.5kg
    featured: true,
  },
  {
    id: "5",
    name: "Dyson V15 Detect",
    category: "appliances",
    price: 749,
    image: "/dyson-v15-vacuum-cleaner-premium.jpg",
    description: "Aspiradora sin cable con tecnología de detección láser",
    brand: "Dyson",
    rating: 4.6,
    reviews: 876,
    inStock: true,
  },
  {
    id: "6",
    name: "Nespresso Vertuo",
    category: "appliances",
    price: 299,
    image: "/nespresso-vertuo-coffee-machine-premium.jpg",
    description: "Cafetera de cápsulas con sistema Centrifusion",
    brand: "Nespresso",
    rating: 4.5,
    reviews: 1432,
    inStock: true,
  },
  {
    id: "7",
    name: "Chanel N°5",
    category: "perfumes",
    price: 159,
    image: "/chanel-no-5-perfume-bottle-luxury.jpg",
    description: "El perfume icónico que define la elegancia atemporal",
    brand: "Chanel",
    rating: 4.9,
    reviews: 3421,
    inStock: true,
    featured: true,
  },
  {
    id: "8",
    name: "Dior Sauvage",
    category: "perfumes",
    price: 135,
    image: "/dior-sauvage-perfume-bottle-luxury.jpg",
    description: "Fragancia masculina fresca e intensa inspirada en espacios abiertos",
    brand: "Dior",
    rating: 4.8,
    reviews: 2876,
    inStock: true,
  },
  {
    id: "9",
    name: "Tom Ford Black Orchid",
    category: "perfumes",
    price: 189,
    image: "/tom-ford-black-orchid-perfume-luxury.jpg",
    description: "Fragancia oriental oscura y sensual con notas de orquídea negra",
    brand: "Tom Ford",
    rating: 4.7,
    reviews: 1654,
    inStock: true,
  },
  {
    id: "10",
    name: 'iPad Pro 12.9"',
    category: "electronics",
    price: 1099,
    image: "/ipad-pro-12-9-tablet-premium.jpg",
    description: "Tablet profesional con chip M2 y pantalla Liquid Retina XDR",
    brand: "Apple",
    rating: 4.8,
    reviews: 765,
    inStock: true,
  },
  {
    id: "11",
    name: "Bose QuietComfort Ultra",
    category: "electronics",
    price: 429,
    image: "/bose-quietcomfort-ultra-headphones-premium.jpg",
    description: "Auriculares con audio espacial inmersivo y cancelación de ruido",
    brand: "Bose",
    rating: 4.7,
    reviews: 987,
    inStock: true,
  },
  {
    id: "12",
    name: "LG French Door Refrigerator",
    category: "appliances",
    price: 2999,
    image: "/lg-french-door-refrigerator-stainless-steel-luxury.jpg",
    description: "Refrigerador inteligente con dispensador InstaView y Wi-Fi",
    brand: "LG",
    rating: 4.6,
    reviews: 432,
    inStock: true,
  },
]
